### ISSUE TITLE
make setup error report

### ISSUE THREAD

**Issue by nicedayd** [efabless/caravel_user_project#269] opened 2023-05-28 07:38 UTC
### Discussed in https://github.com/efabless/caravel_user_project/discussions/268

<div type='discussions-op-text'>

<sup>Originally posted by **nicedayd** May 28, 2023</sup>
Hello,
Could somebody support to fix following issue?
Background: run the [caravel_user_project](https://github.com/efabless/caravel_user_project/) setup in my laptop in Win10 with make command; installed MinGW to support "make" in win10. 
Problem: when run the make setup, it reported following error
---------
FIND: Parameter format not correct
FIND: Parameter format not correct
FIND: Parameter format not correct
make -f /caravel/Makefile setup
make[1]: Entering directory 'C:/GitHub Study/caravel_user_project'
make[1]: /caravel/Makefile: No such file or directory
make[1]: *** No rule to make target '/caravel/Makefile'.  Stop.
make[1]: Leaving directory 'C:/GitHub Study/caravel_user_project'
Makefile:40: recipe for target 'setup' failed
make: *** [setup] Error 2

![image](https://github.com/efabless/caravel_user_project/assets/130479288/65845bbb-27e8-4fa2-aeb1-841b61e510f4)

</div>

**Comment by adrienluitot** [comment] 2023-09-12 11:56
This is a duplicate of #268, it should be closed or deleted. @marwaneltoukhy maybe ?

**Comment by marwaneltoukhy** [comment] 2023-09-21 11:58
Thank you @adrienluitot

**Closed by marwaneltoukhy** 2023-09-21 11:58 UTC
Labels: duplicate
